redhat-exd-rebuilds/estuary

- src/app/app.module.ts
- src/app/pipes/keyvaluepairs.ts
- src/app/pipes/nodedisplay.ts
- src/app/pipes/propertydisplay.ts
- src/app/story/storysidebar/storysidebar.component.html
We'll tweak it later but for now this is good enough.
> Properly show relationships in the properties sidebar

- package.json
- src/app/app.module.ts
- src/app/pipes/nodedisplay.ts
- src/app/story/story.component.css
- src/app/story/storyrow/storyrow.component.css
- src/app/story/storyrow/storyrow.component.html
- src/app/story/storyrow/storyrow.component.ts
> Rewrite the story diagram

- src/app/app.module.ts
- src/app/pipes/nodedisplay.ts
- src/app/story/story.component.css
- src/app/story/storyrow/storyrow.component.css
- src/app/story/storysidebar/storysidebar.component.css
- src/app/story/storysidebar/storysidebar.component.html
- src/app/story/storysidebar/storysidebar.component.ts
Review this commit by commit so that it makes more sense.
> Address some of the UX feedback

- src/app/alert/alert.component.css
- src/app/alert/alert.component.html
- src/app/alert/alert.component.ts
- src/app/app.module.ts
- src/app/search/search.component.html
- src/app/search/search.component.ts
- src/app/story/story.component.html
- src/app/story/story.component.ts
- src/styles.css
> Add alerts for errors!

- src/app/story/storysidebar/storysidebar.component.css
> Some CSS improvements

- src/app/pipes/nodedisplay.ts
- src/app/story/storyrow/storyrow.component.ts
Related to: https://github.com/release-engineering/purview-api/pull/90
> Rename ContainerBuilds to ContainerBuild

- .travis.yml
- src/app/services/search.service.spec.ts
- src/app/services/story.service.spec.ts
- tsconfig.json
This will be the first of many PRs adding unit tests. This one is really to just get TravisCI running some basic unit tests.
> Add basic unit tests for the services

- src/app/app.module.ts
- src/app/pipes/nodedisplay.ts
- src/app/pipes/propertydisplay.ts
- src/app/story/story.component.spec.ts
- src/app/story/storysidebar/story.sidebar.component.spec.ts
- src/app/story/storysidebar/storysidebar.component.css
- src/app/story/storysidebar/storysidebar.component.html
- src/app/story/storysidebar/storysidebar.component.ts
Please review this commit by commit to see what is going on in the PR
> Address UX feedback on the sidebar

- src/app/models/story.type.ts
- src/app/search/search.component.ts
- src/app/services/story.service.spec.ts
- src/app/story/story.component.html
- src/app/story/story.component.ts
- src/app/story/test.data.ts
* Support the latest API schema
* Stop displaying the search options for Container Build and Freshmaker Event
> Support the latest API schema and another fix

- src/app/story/storyrow/storyrow.component.css
- src/app/story/storyrow/storyrow.component.html
- src/app/story/storyrow/storyrow.component.spec.ts
- src/app/story/storyrow/storyrow.component.ts
- src/app/story/storysidebar/story.sidebar.component.spec.ts
- src/app/story/storysidebar/storysidebar.component.css
- src/app/story/storysidebar/storysidebar.component.html
- src/assets/circle_multi.svg
- src/assets/circle_single.svg
- src/styles.css
> Refactor the story page based on feedback from the UX team

- src/app/models/story.type.ts
- src/app/story/story.component.html
- src/app/story/test.data.ts
Relates to https://github.com/release-engineering/estuary-api/pull/167
@sarah256 could you please review?
> Support the new correlated nodes API format

- src/app/alert/alert.component.ts
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/models/story.type.ts
- src/app/navbar/navbar.component.html
- src/app/pipes/nodedisplay.ts
- src/app/pipes/propertydisplay.ts
- src/app/search/search.component.ts
- src/app/services/search.service.ts
- src/app/services/siblings.service.spec.ts
- src/app/services/siblings.service.ts
- src/app/services/story.service.ts
- src/app/story/siblings/siblings.component.css
- src/app/story/siblings/siblings.component.html
- src/app/story/siblings/siblings.component.spec.ts
- src/app/story/siblings/siblings.component.ts
- src/app/story/story.component.spec.ts
- src/app/story/story.component.ts
- src/app/story/storyrow/storyrow.component.html
- src/app/story/storyrow/storyrow.component.ts
- src/app/story/storysidebar/story.sidebar.component.spec.ts
- src/app/story/storysidebar/storysidebar.component.ts
- src/app/story/test.data.ts
This also has some somewhat unrelated fixes that made this easier to develop. Those are separated by commit.
> Add the siblings table view

- src/app/story/story.component.html
- src/app/story/story.component.spec.ts
- src/app/story/story.component.ts
- src/app/story/storyrow/storyrow.component.css
- src/app/story/storyrow/storyrow.component.html
- src/app/story/storyrow/storyrow.component.spec.ts
- src/app/story/storyrow/storyrow.component.ts
> Show all siblings in the story regardless of the direction

- src/app/app.module.ts
- src/app/search/search.component.spec.ts
- src/app/story/siblings/siblings.component.spec.ts
- src/app/story/story.component.spec.ts
Use ToastNotificationModule instead of NotificationModule to remove the deprecation warning
> Use ToastNotificationModule instead of NotificationModule

- src/app/story/siblings/siblings.component.css
- src/app/story/siblings/siblings.component.html
- src/app/story/siblings/siblings.component.ts
I can't think of a way of how to unit test this since clicking on the button triggers a download.  I may ask on StackOverflow but for the time being, I'd like to get this feature out without the unit test.
@yashvardhannanavati and @sarah256 could you please review?
> Add an export to CSV button to the siblings table

- package.json
- src/app/app-routing.module.ts
- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/navbar/navbar.component.css
- src/app/navbar/navbar.component.html
- src/app/navbar/navbar.component.ts
- src/app/services/auth-guard.service.spec.ts
- src/app/services/auth-guard.service.ts
- src/app/story/story.component.spec.ts
- src/environments/environment.dev.ts
- src/environments/environment.local-prod-api.ts
- src/environments/environment.prod.ts
- src/environments/environment.stage.ts
- src/environments/environment.ts
> Add optional OpenID Connect authentication

- src/app/tables/artifacts-table/artifacts-table.component.spec.ts
- src/app/tables/table.component.html
- src/app/tables/table.component.spec.ts
- src/app/tables/table.component.ts
- src/app/tables/tests-table/tests-table.component.html
- src/app/tables/tests-table/tests-table.component.spec.ts
- src/app/tables/tests-table/tests-table.component.ts
> Add a link to the OSCI dashboard on OSCI Greenwave test results

- src/app/tables/table.component.css
- src/app/tables/table.component.html
- src/app/tables/table.component.spec.ts
I would like to point out that I don't really like the "margin-left" part. But I couldn't find a nicer way to do that...
Did you ever consider using "flex-box" to align elements?
> Add label with num of shown elements in the table

- src/app/pipes/nodedisplay.ts
- src/app/tables/artifacts-table/artifacts-table.component.ts
Signed-off-by: gnaponie <gnaponie@redhat.com>
> Default columns for Freshmaker builds

- src/app/app-routing.module.ts
- src/app/app.component.spec.ts
- src/app/app.module.ts
- src/app/recents/recents.component.css
- src/app/recents/recents.component.html
- src/app/recents/recents.component.ts
- src/app/tables/artifacts-table/artifacts-table.component.html
- src/app/tables/artifacts-table/artifacts-table.component.spec.ts
- src/app/tables/artifacts-table/artifacts-table.component.ts
- src/app/tables/table.component.html
- src/app/tables/table.component.spec.ts
- src/app/tables/table.component.ts
- src/app/tables/tests-table/tests-table.component.spec.ts
- src/styles.css
> Recents table added on front end with nav tabs

- src/app/recents/recents.component.spec.ts
- src/app/story/storyrow/storyrow.component.css
- src/app/story/storyrow/storyrow.component.html
- src/app/story/storyrow/storyrow.component.spec.ts
- src/app/story/storysidebar/story.sidebar.component.spec.ts
Looks like:
(and similarly on mobile)
> Add creation times of artifacts on stories

- src/app/story/story.component.spec.ts
- src/app/story/storyrow/storyrow.component.html
- src/app/story/test.data.ts
> On stubbed out artifacts, tell user that timestamp information is unavailable

- src/app/story/story.component.spec.ts
- src/app/story/storyrow/storyrow.component.css
- src/app/story/storyrow/storyrow.component.html
- src/app/story/storyrow/storyrow.component.spec.ts
- src/app/story/test.data.ts
Review this per commit to see the individual changes.
> Fix display issues with the artifact's timeline timestamp

- src/app/app.module.ts
- src/app/pipes/timedisplay.ts
- src/app/story/story.component.html
- src/app/story/story.component.spec.ts
- src/app/story/storyrow/storyrow.component.css
- src/app/story/storyrow/storyrow.component.html
- src/app/story/storyrow/storyrow.component.spec.ts
- src/app/story/storyrow/storyrow.component.ts
- src/app/story/storyrow/totaltimes/totaltimes.component.css
- src/app/story/storyrow/totaltimes/totaltimes.component.html
- src/app/story/storyrow/totaltimes/totaltimes.component.spec.ts
- src/app/story/storyrow/totaltimes/totaltimes.component.ts
> Add total times to story and display them

- src/app/app.component.spec.ts
- src/app/notification/notification.component.css
- src/app/pipes/timedisplay.ts
- src/app/story/story.component.html
- src/app/story/story.component.spec.ts
- src/app/story/story.component.ts
- src/app/story/storyrow/storyrow.component.css
- src/app/story/storyrow/storyrow.component.html
- src/app/story/storyrow/storyrow.component.spec.ts
- src/app/story/storyrow/storyrow.component.ts
- src/app/story/storyrow/totaltimes/totaltimes.component.spec.ts
- src/app/story/storysidebar/storysidebar.component.css
- src/app/story/test.data.ts
- src/assets/clock.svg
> Add wait times between artifacts

- src/app/story/story.component.ts
Based on [FACTORY-2529](https://projects.engineering.redhat.com/browse/FACTORY-2529)
> Update tab titles based on artifact selected

- src/app/tables/tests-table/tests-table.component.spec.ts
- src/app/tables/tests-table/tests-table.component.ts
In regards to [FACTORY-4862](https://projects.engineering.redhat.com/browse/FACTORY-4862)
> Show the same CVP logs link as ResultsDB

- src/app/tables/tests-table/tests-table.component.ts
Signed-off-by: gnaponie <gnaponie@redhat.com>
> Small refactoring for performance improvements

- src/app/tables/tests-table/tests-table.component.spec.ts
- src/app/tables/tests-table/tests-table.component.ts
See each commit message for specific details of the changes.
> Minor changes to the test results page

- src/app/tables/artifacts-table/artifacts-table.component.ts
This is based on the discussion in IRC.
> Add "State Name" and "State Reason" as default columns for Freshmaker builds

- .travis.yml
This will enable Estuary to be updated to Angular 8.
> Use nodejs:10 in TravisCI

- .travis.yml
- src/app/tables/tests-table/tests-table.component.spec.ts
- src/app/tables/tests-table/tests-table.component.ts
> Add Greenwave decision summary to test results table
